- name: Create cadvisor container
  community.docker.docker_container:
    name: cadvisor
    image: gcr.io/cadvisor/cadvisor
    detach: true
    privileged: true
    restart_policy: unless-stopped
    ports:
      - 8888:8080
    devices:
      - /dev/kmsg
    volumes:
      - /:/rootfs:ro
      - /dev/disk:/dev/disk:ro
      - /sys:/sys:ro
      - /var/run:/var/run:ro
      - /var/lib/docker:/var/lib/docker:ro

- 