# hosts: all
# tasks:
#   - name: Install common packages
#     apt:
#       name: "{{ item }}"
#       state: present
#     with_items:
#       - curl

- hosts: control
  become: true
  connection: local
  pre_tasks:
    - name: Create group network
      community.docker.docker_network:
        name: control
        attachable: true
  roles:
    - container
    - prometheus
    - grafana

- hosts: pod
  become: true
  roles:
    - container
    - metric