- name: Create NodeExporter container
  community.docker.docker_container:
    name: node-exporter
    image: quay.io/prometheus/node-exporter
    restart_policy: unless-stopped
    detach: true
    command: |
      --path.rootfs=/host
    pid_mode: host
    network_mode: host
    volumes:
      - /:/host:ro,rslave
