# Generated by Django 4.2.3 on 2023-07-26 04:40

from django.db import migrations, models
import docker_mgmt.remotes.ansible
import docker_mgmt.remotes.setup


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnsibleRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('path', models.CharField(max_length=250, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            bases=(models.Model, docker_mgmt.remotes.ansible.Role),
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=200)),
                ('ip_address', models.CharField(max_length=200)),
                ('cpu', models.JSONField(blank=True, null=True)),
                ('memory_total', models.IntegerField(blank=True, null=True)),
                ('disks', models.JSONField(blank=True, null=True)),
                ('labels', models.CharField(default='', max_length=200)),
                ('roles', models.ManyToManyField(blank=True, null=True, to='baremetal.ansiblerole')),
            ],
            bases=(models.Model, docker_mgmt.remotes.setup.Server),
        ),
    ]
