# Generated by Django 4.2.3 on 2023-07-27 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baremetal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='server',
            old_name='hostname',
            new_name='name',
        ),
    ]
