# Generated by Django 4.2.3 on 2023-07-28 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baremetal', '0002_rename_hostname_server_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='disks',
            field=models.JSONField(blank=True, help_text='디스크 정보 (dev: 디바이스, size: 크기(B), used: 사용량(B))', null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='labels',
            field=models.CharField(default='', help_text='레이블', max_length=200),
        ),
        migrations.AlterField(
            model_name='server',
            name='memory_total',
            field=models.IntegerField(blank=True, help_text='총 메모리 용량 (B)', null=True),
        ),
    ]
