# Generated by Django 4.2.4 on 2023-08-05 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baremetal', '0003_alter_server_disks_alter_server_labels_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ansiblerole',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='ansiblerole',
            name='path',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='server',
            name='ip_address',
            field=models.CharField(help_text='서버의 IP 주소 혹은 도메인 이름', max_length=200, unique=True),
        ),
    ]
