# Generated by Django 4.2.4 on 2023-08-05 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baremetal', '0004_alter_ansiblerole_name_alter_ansiblerole_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='labels',
            field=models.CharField(blank=True, default='', help_text='레이블', max_length=200),
        ),
    ]
