- name: Preinstall apt keyring
  command: install -m 0755 -d /etc/apt/keyrings

- name: Set apt keyring
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    keyring: /etc/apt/keyrings/docker.gpg
    state: present

- name: Add apt gpg repository
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release}} stable"
    state: present

- name: Install packages
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    update_cache: yes

- name: Set docker permissions to user
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes

- name: Make user docker directory
  file:
    path: "/home/{{ ansible_user }}/.docker"
    state: directory
    mode: g+rwx
    recurse: yes

- name: Enable docker as systemd daemon
  systemd:
    name: docker
    state: restarted
    enabled: yes

- name: Enable containerd as systemd daemon
  systemd:
    name: containerd
    state: restarted
    enabled: yes